Write-Host "1) npx wrangler login"
Write-Host "2) npx wrangler d1 create researchvault-patent-db"
Write-Host "3) Copy database_id into wrangler.toml"
Write-Host "4) npx wrangler r2 bucket create researchvault-patent-private"
Write-Host "5) npx wrangler d1 migrations apply researchvault-patent-db --remote"
Write-Host "6) npx wrangler secret put OTP_PEPPER"
Write-Host "   npx wrangler secret put SESSION_PEPPER"
Write-Host "   npx wrangler secret put EVIDENCE_HMAC_SECRET"
Write-Host "   npx wrangler secret put RESEND_API_KEY"
Write-Host "7) npx wrangler deploy"
