import{error,nowSec,sanitizeFilename,sha256Hex,uid}from'./security.js';
import{audit}from'./db.js';

const BLOCKED_EXT=new Set(['exe','msi','bat','cmd','com','scr','js','mjs','html','htm','php','sh','ps1','vbs','jar']);
const ALLOWED_EXT=new Set(['pdf','doc','docx','txt','rtf','png','jpg','jpeg','webp','zip','step','stp','iges','igs','dxf','dwg','sch','kicad_sch','brd','json','csv']);
const ENC_VERSION=1;

function ext(name){const i=name.lastIndexOf('.');return i<0?'':name.slice(i+1).toLowerCase()}
function safeCategory(v){return['identity','disclosure','nda','contract','report','filing','signature','payment_proof','other'].includes(v)?v:'other'}
function magicOkay(bytes,extension){const b=new Uint8Array(bytes.slice(0,8));if(extension==='pdf')return b[0]===0x25&&b[1]===0x50&&b[2]===0x44&&b[3]===0x46;if(extension==='png')return b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47;if(['jpg','jpeg'].includes(extension))return b[0]===0xff&&b[1]===0xd8&&b[2]===0xff;if(['docx','zip'].includes(extension))return b[0]===0x50&&b[1]===0x4b;return true}
function asBytes(value){if(typeof value==='string')return new TextEncoder().encode(value);if(value instanceof ArrayBuffer)return new Uint8Array(value);if(ArrayBuffer.isView(value))return new Uint8Array(value.buffer,value.byteOffset,value.byteLength);throw new Error('Unsupported private storage value')}
function hexBytes(hex){const s=String(hex||'').trim();if(!/^[a-fA-F0-9]{64}$/.test(s))throw new Error('FILE_ENCRYPTION_KEY must be 64 hex characters');const out=new Uint8Array(32);for(let i=0;i<32;i++)out[i]=parseInt(s.slice(i*2,i*2+2),16);return out}
async function encryptionKey(env){return crypto.subtle.importKey('raw',hexBytes(env.FILE_ENCRYPTION_KEY),{name:'AES-GCM'},false,['encrypt','decrypt'])}

export async function putPrivate(env,key,value,metadata={}){const plain=asBytes(value),iv=crypto.getRandomValues(new Uint8Array(12)),k=await encryptionKey(env),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,plain)),packed=new Uint8Array(1+iv.length+cipher.length);packed[0]=ENC_VERSION;packed.set(iv,1);packed.set(cipher,13);await env.FILES.put(key,packed,{metadata:{...metadata,encryption:'AES-256-GCM-v1'}})}
export async function getPrivate(env,key){const packed=await env.FILES.get(key,'arrayBuffer');if(!packed)return null;const bytes=new Uint8Array(packed);if(bytes.length<30||bytes[0]!==ENC_VERSION)throw new Error('Invalid encrypted object');const iv=bytes.slice(1,13),cipher=bytes.slice(13),k=await encryptionKey(env);return crypto.subtle.decrypt({name:'AES-GCM',iv},k,cipher)}
export async function deletePrivate(env,key){await env.FILES.delete(key)}

export async function storeMultipartDocument(req,env,caseRow,user,admin=false){const form=await req.formData(),file=form.get('file');if(!(file instanceof File))return{response:error('file is required')};const category=safeCategory(String(form.get('category')||'other')),filename=sanitizeFilename(file.name),extension=ext(filename);if(!ALLOWED_EXT.has(extension)||BLOCKED_EXT.has(extension))return{response:error('File type not allowed',415,'unsupported_file')};const max=Number(env.MAX_UPLOAD_BYTES||15728640);if(file.size>max)return{response:error(`File exceeds ${max} bytes`,413,'file_too_large')};const buffer=await file.arrayBuffer();if(!magicOkay(buffer,extension))return{response:error('File signature does not match extension',415,'invalid_file_signature')};const digest=await sha256Hex(buffer),id=uid('doc'),key=`quarantine/${caseRow.id}/${category}/${Date.now()}-${id}-${filename}`;await putPrivate(env,key,buffer,{originalName:filename,sha256:digest,caseId:caseRow.id,category});await env.DB.prepare(`INSERT INTO patent_documents(id,case_id,owner_user_id,category,filename,object_key,content_type,size_bytes,sha256,security_status,visibility,created_at) VALUES(?,?,?,?,?,?,?,?,?,'quarantine','private',?)`).bind(id,caseRow.id,user.id,category,filename,key,file.type||'application/octet-stream',file.size,digest,nowSec()).run();await audit(env,{caseId:caseRow.id,actorType:admin?'admin':'client',actorId:user.id,eventType:'document_uploaded',meta:{document_id:id,category,filename,size:file.size,sha256:digest}});return{document:{id,category,filename,size_bytes:file.size,sha256:digest,security_status:'quarantine'}}}

export async function downloadDocument(env,doc,filename){const value=await getPrivate(env,doc.object_key);if(!value)return error('Document object missing',404);return new Response(value,{headers:{'content-type':'application/octet-stream','content-disposition':`attachment; filename*=UTF-8''${encodeURIComponent(filename||doc.filename)}`,'cache-control':'no-store','x-content-type-options':'nosniff'}})}

export async function storeSignatureImage(env,caseId,dataUrl){if(!dataUrl||!String(dataUrl).startsWith('data:image/png;base64,'))return{key:null,sha:null};const raw=atob(String(dataUrl).split(',')[1]);if(raw.length>500000)throw new Error('signature_too_large');const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const sha=await sha256Hex(bytes),key=`signatures/${caseId}/${Date.now()}-${uid('sig')}.png`;await putPrivate(env,key,bytes,{sha256:sha,caseId,type:'signature'});return{key,sha}}
